version: "3.8"
services:
  web:
    tty: true
    stdin_open: true
    build:
      context: .
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=db
    restart: unless-stopped
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./tmp/database:/var/lib/postgresql/data
