version: "3.8"
services:
    database:
        image: postgres
        env_file:
            - .env
        ports:
            - "5432:5432"
        volumes:
            - ./volumes/database:/var/lib/postgresql/data
    web:
        build:
            context: .
            dockerfile: Dockerfile
        env_file:
            - .env
        environment:
            - POSTGRES_HOST=database
        volumes:
            - .:/app
        ports:
            - "3000:3000"
        depends_on:
            - database
